FORMAT: 1A
HOST: https://api.test.paysafe.com/

# Payment Hub 

## Getting Started

Paysafe Payment Hub encapsulates integration with multiple payment methods into a single API 
that simplifies the development effort for a new payment method integration to bare minimum 
or even none in certain cases.

The following payment methods are supported

- Card Payments
- Skrill
- Neteller
- PaysafeCard
- PaysafeCash
- Guaranteed ACH
- Sightline Prepaid Cards

# User [/user]

+ Attributes (PaymentHandleRequest)

# Data Structures

## PaymentHandleRequest (object)

+ merchantRefNum: merchantRef-1234
+ amount: 100
+ currency: CAD
+ redirectUrl: https://www.skrill.com - This is required only in case of Payment methods which has redirection
+ savePaymentInstrument: true(boolean) - This should be true if we need to store the payment instrument at Paysafe side. This is supported only for some PaymentMethods
+ customer - Customer information is mandatory if savePaymentInstrument is set to true
 - id: Gt56fR6 - Id is enough, and if id is not present, customer details like firstName, lastName, email ... has to be provided,if id is specified, the additional details provided will be overwritten to existing customer profile?
 - firstName: test
 - lastname: user
 - dateOfBirth: year,month,day(array)
 - email: john.smith@email.com
+ billingAddress
 - id: DF45FDtrR
 - nickname: home
 - street: 100 queen
 - street2: unit 201
 - city: Toronto
 - zip: MSH 2N2
 - country: CA
 - state: ON
+ paymentChannel: CARD,SKRILL, PAYSAFE_CASH, PAYSAFE_CARD,GAURENTEED_ACH,SIGHTLINE(enum)
+ metaData - This Metadata will be passed to respective Payment channel API, if it supports to show some additional inputs in case of redirects to their UI
 - key1: value1
+ reusable: false(boolean)
+ descriptor: transaction for abcd

+ Attributes (PaymentHandleResponse)

# Data Structures

## PaymentHandleResponse (object)

+ id: TGFVRedfghy875redfghnED
+ merchantRefNum: merchantRef-1234
+ amount: 100
+ currency: CAD
+ action: REDIRECT,NONE,CUSTOM(enum) - what action checkout needs to do
+ status: COMPLETED,PENDING,FAILED,REJECTED,CANCELLED(enum) - status of the paymentHandle
+ customer - Customer information will be the same what it receives. It won't be populated with other details using id, as it is using publishable key
 - id: Gt56fR6 - id will be populated if customer is not registered and savePaymentInstrument is set to true
 - firstName: test
 - lastname: user
 - dateOfBirth: year,month,day(array)
 - email: john.smith@email.com
+ billingAddress - This will be the same what the service receives. It won't be populated with other details using id, as it is using publishable key
 - id: DF45FDtrR
 - nickname: home
 - street: 100 queen
 - street2: unit 201
 - city: Toronto
 - zip: MSH 2N2
 - country: CA
 - state: ON
+ paymentChannel: CARD,SKRILL, PAYSAFE_CASH, PAYSAFE_CARD,GAURENTEED_ACH,SIGHTLINE(enum)
+ metaData - populated from input
 - key1: value1
+ reusable: false(boolean)
+ descriptor: transaction for abcd
+ expiryTime: 2014-01-01T23:28:56Z - Expiry time of Payment handle varies between Payment channel

# Group Payment Method APIs

## Fetch Available Payment Methods [/v1/paymentMethods]

### Payment Methods [POST]

+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
                "countryCode" : "CA",
                "currency" : "CAD",
                "amount" : "2000",
                "accountId": "123456789"
            } 

+ Response 200 (application/json)

    + Body

            {
                "countryCode" : "CA",
                "Currency" : "CAD",
                "accountId": "123456789",
                "paymentMethods": [
                {
                  "name": "Card",
                  "type": "scheme",
                  "details": [
                    {
                      "key": "cardNumber",
                      "type": "number"
                    },
                    {
                      "key": "securityCode",
                      "type": "number"
                    },
                    {
                      "key": "encryptedExpiryMonth",
                      "type": "number"
                    },
                    {
                      "key": "encryptedExpiryYear",
                      "type": "number"
                    },
                    {
                      "key": "holderName",
                      "optional": "true",
                      "type": "text"
                    }
                  ]
                },
                {
                  "name" : "Skrill",
                  "type" : "wallet",
                  "operationsSupported" : ["payment", "settlement", "refund"]
                }
              ]
            }
            

# Group Payment Handle APIs


## Payment Handles [/v1/paymenthandles]

The payment handle allows an integrator to accept a variety of payment methods through a single API.

### Create Payment Handle [POST]

+ Request CARD Payment Handle with 3DS enabled (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "amount": "100",
              "merchantRefNum": "ORDER_ID:1231",
              "paymentMethod": "CARD",
              "accountId": "123456789",
              "type": "SINGLE_USE",
              "currency": "CAD",
              "customerIp": "172.0.0.1",
              "merchantUrl": "https://www.example.com",
              "customerId": "Gt56fR6",
              "billingAddress": {
                "addressId": "DF45FDtrR"
              },
              "card": {
              "id" : "paymentInstrumentId1",
                "holderName": "John Smith",
                "cardNum": "4012001036853337",
                "cardExpiry": {
                  "month": "12",
                  "year": "2020"
                },
                "cvv" : "123"
              },
              "three_d_secure": {
                "userAgent": "",
                "acceptedHeader": ""
              }
            }

+ Response 200 (application/json)

    + Body

            {
              "id": "ph_TGFVRedfghy875redfghnED",
              "amount": "100",
              "merchantRefNum": "merchantRef-1234",
              "currency": "CAD",
              "customerIp": "172.0.0.1",
              "accountId": "123456789",
              "flow": "redirect",
              "customer": {
                "firstName": "John",
                "lastName": "Smith",
                "dateOfBirth": {
                  "year": 1981,
                  "month": 10,
                  "day": 24
                },
                "email": "john.smith@email.com"
              },
              "billingAddress": {
                "nickName": "Home",
                "street": "100 Queen",
                "street2": "Unit 200",
                "city": "Toronto",
                "zip": "M5H 2N2",
                "country": "CA",
                "state": "ON"
              },
              "paymentMethod": "CARD",
              "type": "SINGLE_USE",
              "card": {
                "id" : "paymentInstrumentId1",
                "holderName": "John Smith",
                "lastDigits": "1111",
                "cardExpiry": {
                  "month": "12",
                  "year": "2020"
                }
              },
              "redirect": {
                 "url" : "acsurl",
                 "method" : "POST",
                 "formParameters" : {
                 "paReq" : "eJxVUttOwkAQ/RXCO91LS2nJsEmVqBgwRAlGX0izndgGe2G7pfD37kIr+jZn",
                 "TermURL" : "https://api.paysafe.com/v1/paymenthandles/callback/card/3ds",
                 "MD" : "identifier_to_idenity_currentSession"
             },
            "headers" : {
                "Content-Type" : "application/x-www-form-urlencoded"
             }
            },
            "three_d_secure": {
                "enrollmentStatus": "Y"
              }
            }
            
+ Request Card payment handle creation without 3DS (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
                "amount": "100",
                "accountId": "123456789",
                "customer": {
                    "firstName": "John",
                    "lastName": "Smith",
                    "dateOfBirth": {
                        "year": 1981,
                        "month": 10,
                        "day": 24
                    },
                    "email": "john.smith@email.com"
                },
                "billingAddress": {
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON"
                },
                "paymentMethod": "CARD",
                "type": "SINGLE_USE",
                "card": {
                    "id" : "a02e52c7-c991-4418-966a-b62989cb0eae",
                    "holderName": "John Smith",
                    "cardNum": "4111 1111 1111 1111",
                    "cardExpiry": {
                        "month": "12",
                        "year": "2020"
                    },
                  "cvv" : "123"   
                },
                "three_d_secure": {
                  "userAgent": "",
                  "acceptedHeader": ""
                }
            }

+ Response 200 (application/json)

    + Body

            {
                "id": "ph_TGFVRedfghy875redfghnED",
                "amount": "100",
                "accountId": "123456789",
                "flow": "none",
                "customer": {
                    "firstName": "John",
                    "lastName": "Smith",
                    "dateOfBirth": {
                        "year": 1981,
                        "month": 10,
                        "day": 24
                    },
                    "email": "john.smith@email.com"
                },
                "billingAddress": {
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON"
                },
                "paymentMethod": "CARD",
                "type": "SINGLE_USE",
                "card": {
                    "id" : "a02e52c7-c991-4418-966a-b62989cb0eae",
                    "holderName": "John Smith",
                    "cardNum": "1111",
                    "cardExpiry": {
                        "month": "12",
                        "year": "2020"
                    }
                },
              "three_d_secure": {
                "userAgent": "",
                "acceptedHeader": "",
                "enrollmentStatus": "N"
              }
            }
            
+ Request Skrill Payment Handle creation (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
                "merchantRefNum":"123sdfsdfsdf",
                "amount": "100",
                "accountId": "123456789",
                "storedCredential": {
                     "type": "ADHOC",
                     "occurance": "INITIAL"
                },
                "profile": {
                    "firstName": "John",
                    "lastName": "Smith",
                    "middleName": "sdfsd",
                    "phone": "3245678",
                    "gender": "MALE",
                    "nationality": "INDIAN",
                    "cellPhone": "1923218328",
                    "locale": ""
                    "dateOfBirth": {
                        "year": 1981,
                        "month": 10,
                        "day": 24
                    },
                    "email": "john.smith@email.com"
                },
                "billingAddress": {
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON",
                    "phone": "345345435",
                    "recipientName": ""
                },
                "paymentType": "SKRILL",
                "currency": "USD",
                "returnUrl": "www.merchanturl.com",
                "skrill": {
                    "consumerId": "john.doe@email.com",
                    "recipientDescription":"logo_url_alt_text",
                    "language":"EN",
                    "logoUrl":"http://www.paysafe.com/icon.jpg",
                    "detail1Description":"Details 1 description",
                    "detail1Text":"Details 1 text"
                }
            }

+ Response 200 (application/json)

    + Body

            {
                "id": "ph_TGFVRedfghy875redfghnED",
                "status": "PENDING",
                "accountId": "123456789",
                "amount": "100",
                "merchantRefNum": "12345",
                "storedCredential": {
                     "type": "ADHOC",
                     "occurance": "INITIAL"
                },
                "profile": {
                    "id": "12345",
                    "status": "PAYABLE",
                    "merchantCustomerId": "JSHDDS",
                    "paymentToken": "HSAFDYSFD",
                    "firstName": "John",
                    "lastName": "Smith",
                    "middleName": "sdfsd",
                    "phone": "3245678",
                    "gender": "MALE",
                    "nationality": "INDIAN",
                    "cellPhone": "1923218328",
                    "locale": ""
                    "dateOfBirth": {
                        "year": 1981,
                        "month": 10,
                        "day": 24
                    },
                    "email": "john.smith@email.com"
                },
                "billingAddress": {
                    "id": "12345",
                    "status": "PAYABLE",
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON",
                    "phone": "345345435",
                    "recipientName": ""
                },
                "paymentType": "SKRILL",
                "usage": "SINGLE_USE",
                "action": "REDIRECT",
                "executionMode": "SYNCHRONOUS",
                 "links": [
                           {
                            "href": "https://www.skrill.com",
                            "rel": "self"
                    }
                  ],
                 "currency": "USD",
                 "returnUrl": "www.merchanturl.com",
                 "descriptor": "dsfdsg",
                 "creationDate": "12-23-1323",
                 "expirationDate": "12-23-3446",
                 "paymentHandleToken": "AJSASGA",
                "skrill": {
                    "consumerId": "john.doe@email.com",
                    "recipientDescription":"logo_url_alt_text",
                    "language":"EN",
                    "logoUrl":"http://www.paysafe.com/icon.jpg",
                    "detail1Description":"Details 1 description",
                    "detail1Text":"Details 1 text"
                }
            }
            
+ Request Neteller Payment Handle creation (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
                "amount": "148",
                "accountId": "123456789",
                "customer": {
                    "firstName": "John",
                    "lastName": "Smith",
                    "dateOfBirth": {
                        "year": 1981,
                        "month": 10,
                        "day": 24
                    },
                    "email": "john.smith@email.com"
                },
                "billingAddress": {
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON"
                },
                "paymentMethod": "NETELLER",
                "type": "SINGLE_USE",
                "neteller": {
                    "consumerId":"neteller.account@example.org",
                    "consumerVerificationId":"123456",
                    "recipientDescription":"logo_url_alt_text",
                    "language":"EN",
                    "logoUrl":"http://www.paysafe.com/icon.jpg",
                    "detail1Description":"Details 1 description",
                    "detail1Text":"Details 1 text"
                }
            }

+ Response 200 (application/json)

    + Body

            {
                "id": "ph_TGFVRedfghy875redfghnED",
                "amount": "148",
                "accountId": "123456789",
                "customer": {
                    "firstName": "John",
                    "lastName": "Smith",
                    "dateOfBirth": {
                        "year": 1981,
                        "month": 10,
                        "day": 24
                    },
                    "email": "john.smith@email.com"
                },
                "billingAddress": {
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON"
                },
                "paymentMethod": "SKRILL",
                "type": "SINGLE_USE",
                "neteller": {
                    "consumerId":"neteller.account@example.org",
                    "consumerVerificationId":"123456",
                    "recipientDescription":"logo_url_alt_text",
                    "language":"EN",
                    "logoUrl":"http://www.paysafe.com/icon.jpg",
                    "detail1Description":"Details 1 description",
                    "detail1Text":"Details 1 text"
                }
            }
+ Request PaysafeCard Payment Handle creation (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
                "amount": "148",
                "accountId": "123456789",
                "customer": {
                    "firstName": "John",
                    "lastName": "Smith",
                    "dateOfBirth": {
                        "year": 1981,
                        "month": 10,
                        "day": 24
                    },
                    "email": "john.smith@email.com"
                },
                "billingAddress": {
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON"
                },
                "paymentMethod": "PAYSAFE_CARD",
                "type": "SINGLE_USE",
                "paysafecard": {
                    "consumerId": "merchantclientid",
                    "minAgeRestriction": 18,
                    "kycLevelRestriction": "SIMPLE",
                    "countryRestriction": "DE"
                    }
            }

+ Response 200 (application/json)

    + Body

            {
                "id": "ph_TGFVRedfghy875redfghnED",
                "amount": "148",
                "accountId": "123456789",
                "customer": {
                    "firstName": "John",
                    "lastName": "Smith",
                    "dateOfBirth": {
                        "year": 1981,
                        "month": 10,
                        "day": 24
                    },
                    "email": "john.smith@email.com"
                },
                "billingAddress": {
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON"
                },
                "paymentMethod": "PAYSAFE_CARD",
                "type": "SINGLE_USE",
                "paysafecard": {
                    "consumerId": "merchantclientid",
                    "minAgeRestriction": 18,
                    "kycLevelRestriction": "SIMPLE",
                    "countryRestriction": "DE"
                },
                "redirect": {
                    "url": "redirect_url",
                    "method": "GET"
                }
            }
            
+ Request PaysafeCash Payment Handle creation (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
                "amount": "148",
                "accountId": "123456789",
                "customer": {
                    "firstName": "John",
                    "lastName": "Smith",
                    "dateOfBirth": {
                        "year": 1981,
                        "month": 10,
                        "day": 24
                    },
                    "email": "john.smith@email.com"
                },
                "billingAddress": {
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON"
                },
                "paymentMethod": "PAYSAFE_CASH",
                "type": "SINGLE_USE",
                "paysafecash": {
                    "consumerId": "merchantclientid",
                    "minAgeRestriction": 18,
                    "kycLevelRestriction": "SIMPLE",
                    "countryRestriction": "DE"
                    }
            }

+ Response 200 (application/json)

    + Body

            {
                "id": "ph_TGFVRedfghy875redfghnED",
                "amount": "148",
                "accountId": "123456789",
                "customer": {
                    "firstName": "John",
                    "lastName": "Smith",
                    "dateOfBirth": {
                        "year": 1981,
                        "month": 10,
                        "day": 24
                    },
                    "email": "john.smith@email.com"
                },
                "billingAddress": {
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON"
                },
                "paymentMethod": "PAYSAFE_CASH",
                "type": "SINGLE_USE",
               "paysafecash": {
                    "consumerId": "merchantclientid",
                    "minAgeRestriction": 18,
                    "kycLevelRestriction": "SIMPLE",
                    "countryRestriction": "DE"
                }
            }
            
### Fetch Payment Handle [GET /v1/paymenthandles/f343d2bd-f6a6-4a6d-9534-96c0abd97649]


+ Response 200 (application/json)

    + Body

            {
                "id": "f343d2bd-f6a6-4a6d-9534-96c0abd97649",
                "masterMerchantId": "234",
                "merchantRefNum": "13995817730005399",
                "status": "INITIATED",
                "usage": "SINGLE_USE",
                "paymentType": "CARD",
                "action": "REDIRECT",
                "executionMode": "SYNCHRONOUS",
                "amount": 1000,
                "currencyCode": "USD",
                "links": [
                    {
                    "type": "REDIRECT",
                    "url": "http://test.paysafe.com",
                    "method": "POST"
                },
                {
                "type": "RETURN_SUCCESS",
                "url": "http://merchant.com/success",
                 "method": "POST"
            },
            {
                "type": "RETURN_FAILURE",
                "url": "http://merchant.com/failure",
                "method": "POST"
             }
            ],
                "customerIp": "10.10.12.64",
                "savePaymentInstrument": false,
                "merchantDescriptor": {
                "dynamicDescriptor": "Casino slots payin"
             },
                "fmaId": "card-processor-usd-003",
                 "paymentHandleToken": "SCC54RTfi7x5sgjV",
                "creationDate": 1540199745029,
                "billingAddress": {
                    "street": "Wall Street",
                    "street2": "NYSE",
                    "city": "New York",
                    "state": "NY",
                    "country": "US",
                    "zip": "12345"
            },
                "card": {
                    "paymentToken": "SCC54RTfi7x5sgjV"
                }
            }

### Fetch Payment Handle by Merchant Reference Number [GET /v1/paymenthandles?merchantRefNum=13995817730005389&masterMerchantId=234]

+ Response 200 (application/json)

    + Body

            {
                "id": "f343d2bd-f6a6-4a6d-9534-96c0abd97649",
                "masterMerchantId": "234",
                "merchantRefNum": "13995817730005399",
                "status": "INITIATED",
                "usage": "SINGLE_USE",
                "paymentType": "CARD",
                "action": "REDIRECT",
                "executionMode": "SYNCHRONOUS",
                "amount": 1000,
                "currencyCode": "USD",
                "links": [
                    {
                    "type": "REDIRECT",
                    "url": "http://test.paysafe.com",
                    "method": "POST"
                },
                {
                "type": "RETURN_SUCCESS",
                "url": "http://merchant.com/success",
                 "method": "POST"
            },
            {
                "type": "RETURN_FAILURE",
                "url": "http://merchant.com/failure",
                "method": "POST"
             }
            ],
                "customerIp": "10.10.12.64",
                "savePaymentInstrument": false,
                "merchantDescriptor": {
                "dynamicDescriptor": "Casino slots payin"
             },
                "fmaId": "card-processor-usd-003",
                 "paymentHandleToken": "SCC54RTfi7x5sgjV",
                "creationDate": 1540199745029,
                "billingAddress": {
                    "street": "Wall Street",
                    "street2": "NYSE",
                    "city": "New York",
                    "state": "NY",
                    "country": "US",
                    "zip": "12345"
            },
                "card": {
                    "paymentToken": "SCC54RTfi7x5sgjV"
                }
            }

# Group Payment APIs

## Payments [/v1/payments]

Payment API is used to mark the submission of a payment from the customer side. For credit and debit cards, it is equivalent to an authorization while in case of digital wallet transactions, it is used to mark successful transfer of money.


### Create Payment with handle Id [POST]

+ Attributes (PaymentHandleRequest)


+ Request Card Payment with Payment Handle (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
            

    
    + Body

            {
              "merchantRefNum": "merchant tokenization example-789",
              "amount": 1295,
              "dupCheck": false,
              "settleWithAuth": false,
              "partialAuth": {
                "requested": false
              },
              "paymentHandleId": "ph_TGFVRedfghy875redfghnED",
              "customerIp": "204.91.0.12",
              "description": "Magazine subscription"
            }
            
+ Response 200 (application/json)

    + Body

            {
              "id": "14d380a4-e934-4cc8-b49e-a90cc082faa0",
              "merchantRefNum": "merchant tokenization example-789",
              "amount": 1295,
              "settleWithAuth": false,
              "dupCheck": false,
              "partialAuth": {
                "requested": false
              },
              "availableToSettle": 1295,
              "description": "Magazine subscription",
              "authCode": "1234567655",
              "paymentHandle": {
                "id": "ph_TGFVRedfghy875redfghnED",
                "amount": "1295",
                "merchantRefNum": "merchant tokenization example-789",
                "currency": "CAD",
                "customerIp": "204.91.0.12",
                "flow": "redirect",
                "customer": {
                  "firstName": "John",
                  "lastName": "Smith",
                  "dateOfBirth": {
                    "year": 1981,
                    "month": 10,
                    "day": 24
                  },
                  "email": "john.smith@email.com"
                },
                "billingAddress": {
                  "nickName": "Home",
                  "street": "100 Queen",
                  "street2": "Unit 200",
                  "city": "Toronto",
                  "zip": "M5H 2N2",
                  "country": "CA",
                  "state": "ON"
                },
                "paymentMethod": "CARD",
                "type": "SINGLE_USE",
                "card": {
                  "id": "paymentInstrumentId1",
                  "holderName": "John Smith",
                  "lastDigits": "1111",
                  "cardExpiry": {
                    "month": "12",
                    "year": "2020"
                  }
                }
              },
              "txnTime": "2014-12-14T15:12:18Z",
              "currencyCode": "CAD",
              "avsResponse": "MATCH",
              "cvvVerification": "NOT_PROCESSED",
              "status": "COMPLETED"
            }

+ Request Payment with Skrill Payment Handle (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "merchantRefNum": "merchant tokenization example-789",
              "amount": 1295,
              "settleWithAuth": false,
              "paymentHandleId": "LTEyMzYzMjQ3ODg",
              "customerIp": "204.91.0.12",
              "description": "Magazine subscription"
            }
                        
+ Response 200 (application/json)

    + Body

            {
              "id": "a02e52c7-c991-4418-966a-b62989cb0eae",
              "merchantRefNum": "ORDER_ID:1231",
              "amount": 10098,
              "customerIp": "192.0.126.111",
              "paymentHandleId": "LTEyMzYzMjQ3ODg",
              "skrill": {
                "mandateReference": "1000-3232659874-65985698",
                "accountHolderName": "XYZ Company",
                "lastDigits": "66"
              },
              "profile": {
                "firstName": "Joe",
                "lastName": "Smith",
                "email": "Joe.Smith@hotmail.com"
              },
              "billingAddress": {
                "street": "Hoofdstraat 101",
                "city": "Heeswijk-Dinther",
                "country": "NL",
                "zip": "5233 HG",
                "phone": "06-12304567"
              },
              "txnTime": "2014-12-14T15:12:18Z",
              "currencyCode": "EUR",
              "status": "PENDING"
            }
            
+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "merchantRefNum": "merchant tokenization example-789",
              "amount": 1295,
              "settleWithAuth": false,
              "paymentHandleId": "LTEyMzYzMjQ3ODg",
              "customerIp": "204.91.0.12",
              "description": "Magazine subscription"
            }
                        
+ Response 200 (application/json)

    + Body

            {
              "id": "a02e52c7-c991-4418-966a-b62989cb0eae",
              "merchantRefNum": "ORDER_ID:1231",
              "amount": 10098,
              "customerIp": "192.0.126.111",
              "paymentHandleId": "LTEyMzYzMjQ3ODg",
              "skrill": {
                "mandateReference": "1000-3232659874-65985698",
                "accountHolderName": "XYZ Company",
                "lastDigits": "66"
              },
              "profile": {
                "firstName": "Joe",
                "lastName": "Smith",
                "email": "Joe.Smith@hotmail.com"
              },
              "billingAddress": {
                "street": "Hoofdstraat 101",
                "city": "Heeswijk-Dinther",
                "country": "NL",
                "zip": "5233 HG",
                "phone": "06-12304567"
              },
              "txnTime": "2014-12-14T15:12:18Z",
              "currencyCode": "EUR",
              "status": "PENDING"
            }
            
                        
+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "merchantRefNum": "merchant tokenization example-789",
              "amount": 1295,
              "paymentHandleId": "LTEyMzYzMjQ3ODg",
              "customerIp": "204.91.0.12",
              "description": "Magazine subscription"
            }
                        
+ Response 200 (application/json)

    + Body

            {
              "id": "a02e52c7-c991-4418-966a-b62989cb0eae",
              "merchantRefNum": "ORDER_ID:1231",
              "amount": 10098,
              "customerIp": "192.0.126.111",
              "paymentHandleId": "LTEyMzYzMjQ3ODg",
              "sepa": {
                "mandateReference": "1000-3232659874-65985698",
                "accountHolderName": "XYZ Company",
                "lastDigits": "66"
              },
              "profile": {
                "firstName": "Joe",
                "lastName": "Smith",
                "email": "Joe.Smith@hotmail.com"
              },
              "billingAddress": {
                "street": "Hoofdstraat 101",
                "city": "Heeswijk-Dinther",
                "country": "NL",
                "zip": "5233 HG",
                "phone": "06-12304567"
              },
              "txnTime": "2014-12-14T15:12:18Z",
              "currencyCode": "EUR",
              "status": "PENDING"
            }
            
            
### Get Payments [GET /v1/payments/{payment_id}]

Click on Get Payments above to see how to fetch the payments by payment_id.

+ Parameter

   + payment_id (String) - 86dcb68d-cbd0-4878-8da7-ffc0e6554513

+ Response 200 (application/json)

    + Body

            {
              "id": "14d380a4-e934-4cc8-b49e-a90cc082faa0",
              "merchantRefNum": "merchant tokenization example-789",
              "amount": 1295,
              "settleWithAuth": false,
              "dupCheck": false,
              "partialAuth": {
                "requested": false
              },
              "availableToSettle": 1295,
              "description": "Magazine subscription",
              "authCode": "1234567655",
              "paymentHandle": {
                "id": "ph_TGFVRedfghy875redfghnED",
                "amount": "1295",
                "merchantRefNum": "merchant tokenization example-789",
                "currency": "CAD",
                "customerIp": "204.91.0.12",
                "flow": "redirect",
                "customer": {
                  "firstName": "John",
                  "lastName": "Smith",
                  "dateOfBirth": {
                    "year": 1981,
                    "month": 10,
                    "day": 24
                  },
                  "email": "john.smith@email.com"
                },
                "billingAddress": {
                  "nickName": "Home",
                  "street": "100 Queen",
                  "street2": "Unit 200",
                  "city": "Toronto",
                  "zip": "M5H 2N2",
                  "country": "CA",
                  "state": "ON"
                },
                "paymentMethod": "CARD",
                "type": "SINGLE_USE",
                "card": {
                  "id": "paymentInstrumentId1",
                  "holderName": "John Smith",
                  "lastDigits": "1111",
                  "cardExpiry": {
                    "month": "12",
                    "year": "2020"
                  }
                }
              },
              "txnTime": "2014-12-14T15:12:18Z",
              "currencyCode": "CAD",
              "avsResponse": "MATCH",
              "cvvVerification": "NOT_PROCESSED",
              "status": "COMPLETED"
            }
            
### Get Payments by Merchant Reference number [GET /v1/payments?merchantRefNum={merchantRefNum_id}]

Click on above to fetch the payments by merchant refernce number.

+ Parameter

   + merchantRefNum_id (String) - merchant tokenization example-789

+ Response 200 (application/json)

    + Body

            {
              "id": "14d380a4-e934-4cc8-b49e-a90cc082faa0",
              "merchantRefNum": "merchant tokenization example-789",
              "amount": 1295,
              "settleWithAuth": false,
              "dupCheck": false,
              "partialAuth": {
                "requested": false
              },
              "availableToSettle": 1295,
              "description": "Magazine subscription",
              "authCode": "1234567655",
              "paymentHandle": {
                "id": "ph_TGFVRedfghy875redfghnED",
                "amount": "1295",
                "merchantRefNum": "merchant tokenization example-789",
                "currency": "CAD",
                "customerIp": "204.91.0.12",
                "flow": "redirect",
                "customer": {
                  "firstName": "John",
                  "lastName": "Smith",
                  "dateOfBirth": {
                    "year": 1981,
                    "month": 10,
                    "day": 24
                  },
                  "email": "john.smith@email.com"
                },
                "billingAddress": {
                  "nickName": "Home",
                  "street": "100 Queen",
                  "street2": "Unit 200",
                  "city": "Toronto",
                  "zip": "M5H 2N2",
                  "country": "CA",
                  "state": "ON"
                },
                "paymentMethod": "CARD",
                "type": "SINGLE_USE",
                "card": {
                  "id": "paymentInstrumentId1",
                  "holderName": "John Smith",
                  "lastDigits": "1111",
                  "cardExpiry": {
                    "month": "12",
                    "year": "2020"
                  }
                }
              },
              "txnTime": "2014-12-14T15:12:18Z",
              "currencyCode": "CAD",
              "avsResponse": "MATCH",
              "cvvVerification": "NOT_PROCESSED",
              "status": "COMPLETED"
            }
            
# Group Settlement APIs

## Settlements [/v1/auths/{auth_id}/settlements]

Settlement with dupCheck and merchentRefNum

+ Parameter

    + auth_id (String) - Qwdqdasdansdbasdtftoiqwo

### Post Settlement [POST]

1) A regular Settlement, where the initial request was an Authorization that now has to be settled
2) A partial Settlement, where only part of the initial Authorization is settled, leaving the balance to be settled later
3) A Settlement that is split into multiple merchant accounts, for merchant accounts that are configured to do so

+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "merchantRefNum": "merchantRef_2016_04_11_05",
              "dupCheck": true
            }
                        
+ Response 200 (application/json)

    + Body

            {
              "id": "d1fb46ee-2736-4ef5-a724-f263ace75373",
              "merchantRefNum": "merchantRef_2016_04_11_05",
              "amount": 5500,
              "availableToRefund": 5500,
              "dupCheck": true,
              "txnTime": "2017-02-14T15:12:18Z",
              "status": "COMPLETED",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/accounts/123456789/settlements/d1fb46ee-2736-4ef5-a724-f263ace75373"
                }
              ]
            }
            
+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "merchantRefNum": "merchantRef_2016_04_11_05",
              "amount": 2250,
              "dupCheck": true
            }


+ Response 200 (application/json)

    + Body

            {
              "id": "d1fb46ee-2736-4ef5-a724-f263ace75373",
              "merchantRefNum": "merchantRef_2016_04_11_05",
              "amount": 2250,
              "availableToRefund": 2250,
              "dupCheck": true,
              "txnTime": "2017-02-14T15:12:18Z",
              "status": "COMPLETED",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/accounts/123456789/settlements/d1fb46ee-2736-4ef5-a724-f263ace75373"
                }
              ]
            }
            
### Cancel a Settlement [PUT /v1/settlement/{settlement_id}]

1. Settlement with dupCheck and merchentRefNum
2. partial Settlement with amount in Request Body 

+ Parameter

    + settlement_id (String) - Qwdqdasdansdbasdtftoiqwo

+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "status": "CANCELLED"
            }
                        
+ Response 200 (application/json)

    + Body

            {
              "id": "d1fb46ee-2736-4ef5-a724-f263ace75373",
              "txnTime": "2017-02-14T15:12:18Z",
              "status": "CANCELLED",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/accounts/123456789/settlements/d1fb46ee-2736-4ef5-a724-f263ace75373"
                }
              ]
            }

# Group Refund APIs

## Refunds [/v1/payments/{payments_id}/refunds]

The settlement details in case of Card payment method can be sent through Request Body

+ Parameter

    + payments_id (String) - Qwdqdasdansdbasdtftoiqwo

### Post Refund [POST]

A regular Refund
2) A Refund that is split into multiple merchant accounts, for merchant accounts that are configured to do so

+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "merchantRefNum": "merchantRef_2016_04_11_05",
              "amount": 5500,
              "dupCheck": true
            }
                        
+ Response 200 (application/json)

    + Body

            {
              "id": "d1fb46ee-2736-4ef5-a724-f263ace75374",
              "merchantRefNum": "merchantRef_2016_04_11_05",
              "amount": 5500,
              "dupCheck": true,
              "txnTime": "2017-02-14T15:12:18Z",
              "status": "COMPLETED",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/accounts/123456789/refunds/d1fb46ee-2736-4ef5-a724-f263ace75374"
                }
              ]
            }
            
### Cancel Refund [PUT /v1/refunds/{refund_id}]

Click on Cancel a Refund above to see how to submit a Cancel Refund request.

+ Parameter

    + refund_id (String) - Qwdqdasdansdbasdtftoiqwo
    
+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "status": "CANCELLED"
            }
                        
+ Response 200 (application/json)

    + Body

            {
              "id": "d1fb46ee-2736-4ef5-a724-f263ace75374",
              "txnTime": "2017-02-14T15:12:18Z",
              "status": "CANCELLED",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/accounts/123456789/refunds/d1fb46ee-2736-4ef5-a724-f263ace75374"
                }
              ]
            }
            
### Get Refund [GET]

+ Response 200 (application/json)

    + Body

            {
              "id": "d1fb46ee-2736-4ef5-a724-f263ace75374",
              "merchantRefNum": "merchantRef_2016_04_11_05",
              "amount": 5500,
              "dupCheck": true,
              "txnTime": "2017-02-14T15:12:18Z",
              "status": "PENDING",
              "splitpay": [
                {
                  "linkedAccount": "123124124",
                  "amount": 500
                }
              ],
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/accounts/123456789/refunds/d1fb46ee-2736-4ef5-a724-f263ace75374"
                }
              ]
            }
         
# Group Standalone Credits APIs

## Standalone Credits [/v1/standalonecredits]

Standalone Credits allow merchants to issue credits to cardholders without requiring a previous Authorization/Settlement.

### Post Standalone Credit [POST]

1. Credit with original Card information
2. Credit with Payment Token


+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "merchantRefNum": "13995817730005399",
              "amount": 1000,
              "dupCheck": "true",
              "card": {
                "cardNum": "4111111111111111",
                "cardExpiry": {
                  "month": 2,
                  "year": 2019
                }
              },
              "customerIp": "204.91.0.12",
              "description": "Winning payment from Loto",
              "accountId": "123456789"
            }         
+ Response 200 (application/json)

    + Body

            {
              "id": "86dcb68d-cbd0-4878-8da7-ffc0e6554513",
              "merchantRefNum": "13995817730005399",
              "txnTime": "2017-07-06T19:59:17Z",
              "status": "PENDING",
              "amount": 1000,
              "card": {
                "type": "VI",
                "lastDigits": "1111",
                "cardExpiry": {
                  "month": 2,
                  "year": 2019
                }
              },
              "profile": {
                "firstName": "Joe",
                "lastName": "Smith",
                "email": "Joe.Smith@canada.com"
              },
              "billingDetails": {
                "street": "100 Queen Street West",
                "city": "Toronto",
                "state": "ON",
                "country": "CA",
                "zip": "M5H2N2"
              },
              "customerIp": "204.91.0.12",
              "description": "Winning payment from Loto",
              "currencyCode": "CAD",
              "accountId": "123456789",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/standalonecredits/86dcb68d-cbd0-4878-8da7-ffc0e6554513"
                }
              ]
            }
            
+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "merchantRefNum": "merchant 07.05.17_16",
              "amount": 1000,
              "dupCheck": "true",
              "card": {
                "paymentToken": "LTEyMzYzMjQ3ODg"
              },
              "customerIp": "204.91.0.12",
              "description": "Winning payment from Loto",
              "accountId": "123456789"
            }  
            
+ Response 200 (application/json)

    + Body

            {
              "id": "86dcb68d-cbd0-4878-8da7-ffc0e6554513",
              "merchantRefNum": "merchant 07.05.17_16",
              "txnTime": "2017-07-06T19:59:17Z",
              "status": "PENDING",
              "amount": 1000,
              "card": {
                "type": "VI",
                "lastDigits": "1111",
                "cardExpiry": {
                  "month": 2,
                  "year": 2019
                }
              },
              "profile": {
                "firstName": "Joe",
                "lastName": "Smith",
                "email": "Joe.Smith@canada.com"
              },
              "billingDetails": {
                "street": "100 Queen Street West",
                "city": "Toronto",
                "state": "ON",
                "country": "CA",
                "zip": "M5H2N2"
              },
              "customerIp": "204.91.0.12",
              "description": "Winning payment from Loto",
              "currencyCode": "CAD",
              "accountId": "123456789",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/standalonecredits/86dcb68d-cbd0-4878-8da7-ffc0e6554513"
                }
              ]
            }
            
### Cancel Standalone Credit [PUT /v1/standalonecredits/{standalone_credit_id}]

Click on Cancel a Standalone Credit above to see how to submit a Cancel Standalone Credit request.

+ Parameter

    + standalone_credit_id (String) - 86dcb68d-cbd0-4878-8da7-ffc0e6554513
    

+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "status": "CANCELLED"
            }


+ Response 200 (application/json)

    + Body

            {
              "id": "86dcb68d-cbd0-4878-8da7-ffc0e6554513",
              "txnTime": "2017-02-14T15:12:18Z",
              "status": "CANCELLED",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/standalonecredits/86dcb68d-cbd0-4878-8da7-ffc0e6554513"
                }
              ]
            }
            

### Get Standalone Credit [GET]

Click on Get Standalone Credit above to see how to look up a Standalone Credit request using the ID returned in the response to the original request.

+ Response 200 (application/json)

    + Body

            {
              "id": "86dcb68d-cbd0-4878-8da7-ffc0e6554513",
              "merchantRefNum": "merchant 07.05.17_16",
              "txnTime": "2017-07-06T19:59:17Z",
              "status": "PENDING",
              "amount": 1000,
              "card": {
                "type": "VI",
                "lastDigits": "1111",
                "cardExpiry": {
                  "month": 2,
                  "year": 2019
                }
              },
              "profile": {
                "firstName": "Joe",
                "lastName": "Smith",
                "email": "Joe.Smith@canada.com"
              },
              "billingDetails": {
                "street": "100 Queen Street West",
                "city": "Toronto",
                "state": "ON",
                "country": "CA",
                "zip": "M5H2N2"
              },
              "customerIp": "204.91.0.12",
              "description": "Winning payment from Loto",
              "currencyCode": "CAD",
              "accountId": "123456789",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/standalonecredits/86dcb68d-cbd0-4878-8da7-ffc0e6554513"
                }
              ]
            }
            
### Get Standalone Credit Using Merchant Reference Number  [GET /v1/standalonecredits?merchantRefNum=13995817730005399]

Click on Get Standalone Credit Using Merchant Reference Number above to see how to look up a Standalone Credit using the merchant reference number used in the original request.

+ Response 200 (application/json)

    + Body

            {
               "standalonecredits": [
                {
                    "id": "86dcb68d-cbd0-4878-8da7-ffc0e6554513",
                    "merchantRefNum": "13995817730005399",
                    "txnTime": "2017-07-06T19:59:17Z",
                    "status": "PENDING",
                    "amount": 1000,
                    "card": {
                        "type": "VI",
                        "lastDigits": "1111",
                        "cardExpiry": {
                        "month": 2,
                        "year": 2019
                    }
                },
                "profile": {
                    "firstName": "Joe",
                    "lastName": "Smith",
                    "email": "Joe.Smith@canada.com"
                },
                "billingDetails": {
                    "street": "100 Queen Street West",
                    "city": "Toronto",
                    "state": "ON",
                    "country": "CA",
                    "zip": "M5H2N2"
                },
                "customerIp": "204.91.0.12",
                "description": "Winning payment from Loto",
                "currencyCode": "CAD",
                "accountId": "123456789",
                "links": [
                   {
                    "rel": "self",
                    "href": "https://api.test.paysafe.com/cardpayments/v1/standalonecredits/86dcb68d-cbd0-4878-8da7-ffc0e6554513"
                }
                ]
                 }
                ],
                "links": [
                 {
                    "rel": "self",
                    "href": "https://api.test.paysafe.com/cardpayments/v1/standalonecredits?merchantRefNum=merchant 07.05.17_16&limit=2&offset=2&startDate=2017-01-14T15:12:18Z&endDate=2017-04-04T15:12:18Z"
                }
            ]
            }
            


# Group Original Credits APIs

## Original Credits [/v1/originalcredits]

Original Credits allow merchants with specific merchant category codes (MCCs) to issue winnings as credits to cardholders, without requiring a previous Authorization/Settlement.

### Original Credit [POST]

1. An Original Credit request using card information.
2. An Original Credit request using a payment token.

+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "merchantRefNum": "13995817730005399",
              "amount": 1000,
              "dupCheck": "true",
              "card": {
                "cardNum": "4111111111111111",
                "cardExpiry": {
                  "month": 2,
                  "year": 2019
                }
              },
              "customerIp": "204.91.0.12",
              "description": "Winning payment from Loto",
              "accountId": "123456789"
            }         
+ Response 200 (application/json)

    + Body

            {
              "id": "86dcb68d-cbd0-4878-8da7-ffc0e6554513",
              "merchantRefNum": "13995817730005399",
              "txnTime": "2017-07-06T19:59:17Z",
              "status": "PENDING",
              "amount": 1000,
              "card": {
                "type": "VI",
                "lastDigits": "1111",
                "cardExpiry": {
                  "month": 2,
                  "year": 2019
                }
              },
              "profile": {
                "firstName": "Joe",
                "lastName": "Smith",
                "email": "Joe.Smith@canada.com"
              },
              "billingDetails": {
                "street": "100 Queen Street West",
                "city": "Toronto",
                "state": "ON",
                "country": "CA",
                "zip": "M5H2N2"
              },
              "customerIp": "204.91.0.12",
              "description": "Winning payment from Loto",
              "currencyCode": "CAD",
              "accountId": "123456789",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/originalcredits/86dcb68d-cbd0-4878-8da7-ffc0e6554513"
                }
              ]
            }
            
+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "merchantRefNum": "merchant 07.05.17_16",
              "amount": 1000,
              "dupCheck": "true",
              "card": {
                "paymentToken": "LTEyMzYzMjQ3ODg"
              },
              "customerIp": "204.91.0.12",
              "description": "Winning payment from Loto",
              "accountId": "123456789"
            }  
            
+ Response 200 (application/json)

    + Body

            {
              "id": "86dcb68d-cbd0-4878-8da7-ffc0e6554513",
              "merchantRefNum": "merchant 07.05.17_16",
              "txnTime": "2017-07-06T19:59:17Z",
              "status": "PENDING",
              "amount": 1000,
              "card": {
                "type": "VI",
                "lastDigits": "1111",
                "cardExpiry": {
                  "month": 2,
                  "year": 2019
                }
              },
              "profile": {
                "firstName": "Joe",
                "lastName": "Smith",
                "email": "Joe.Smith@canada.com"
              },
              "billingDetails": {
                "street": "100 Queen Street West",
                "city": "Toronto",
                "state": "ON",
                "country": "CA",
                "zip": "M5H2N2"
              },
              "customerIp": "204.91.0.12",
              "description": "Winning payment from Loto",
              "currencyCode": "CAD",
              "accountId": "123456789",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/originalcredits/86dcb68d-cbd0-4878-8da7-ffc0e6554513"
                }
              ]
            }



### Cancel an Original Credit [PUT /v1/originalcredits/{original_credit_id}]

Click on Cancel an Original Credit above to see how to submit a Cancel Original Credit request.

+ Parameter

   + original_credit_id (String) - 86dcb68d-cbd0-4878-8da7-ffc0e6554513

+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
              "status": "CANCELLED"
            }


+ Response 200 (application/json)

    + Body

            {
              "id": "86dcb68d-cbd0-4878-8da7-ffc0e6554513",
              "txnTime": "2017-02-14T15:12:18Z",
              "status": "CANCELLED",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/originalcredits/86dcb68d-cbd0-4878-8da7-ffc0e6554513"
                }
              ]
            }
            

### Get Original Credit [GET]

Click on Get Original Credit above to see how to look up an Original Credit request using the ID returned in the response to the original request.

+ Response 200 (application/json)

    + Body

            {
              "id": "86dcb68d-cbd0-4878-8da7-ffc0e6554513",
              "merchantRefNum": "merchant 07.05.17_16",
              "txnTime": "2017-07-06T19:59:17Z",
              "status": "PENDING",
              "amount": 1000,
              "card": {
                "type": "VI",
                "lastDigits": "1111",
                "cardExpiry": {
                  "month": 2,
                  "year": 2019
                }
              },
              "profile": {
                "firstName": "Joe",
                "lastName": "Smith",
                "email": "Joe.Smith@canada.com"
              },
              "billingDetails": {
                "street": "100 Queen Street West",
                "city": "Toronto",
                "state": "ON",
                "country": "CA",
                "zip": "M5H2N2"
              },
              "customerIp": "204.91.0.12",
              "description": "Winning payment from Loto",
              "currencyCode": "CAD",
              "accountId": "123456789",
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.test.paysafe.com/cardpayments/v1/originalcredits/86dcb68d-cbd0-4878-8da7-ffc0e6554513"
                }
              ]
            }
            
### Get Original Credit Using Merchant Reference Number [GET /v1/originalcredits?merchantRefNum=13995817730005399]

Click on Get Original Credit Using Merchant Reference Number above to see how to look up an Original Credit request using the merchant reference number used in the original request.

+ Response 200 (application/json)

    + Body

            {
               "originalcredits": [
                {
                    "id": "86dcb68d-cbd0-4878-8da7-ffc0e6554513",
                    "merchantRefNum": "13995817730005399",
                    "txnTime": "2017-07-06T19:59:17Z",
                    "status": "PENDING",
                    "amount": 1000,
                    "card": {
                        "type": "VI",
                        "lastDigits": "1111",
                        "cardExpiry": {
                        "month": 2,
                        "year": 2019
                    }
                },
                "profile": {
                    "firstName": "Joe",
                    "lastName": "Smith",
                    "email": "Joe.Smith@canada.com"
                },
                "billingDetails": {
                    "street": "100 Queen Street West",
                    "city": "Toronto",
                    "state": "ON",
                    "country": "CA",
                    "zip": "M5H2N2"
                },
                "customerIp": "204.91.0.12",
                "description": "Winning payment from Loto",
                "currencyCode": "CAD",
                "accountId": "123456789",
                "links": [
                   {
                    "rel": "self",
                    "href": "https://api.test.paysafe.com/cardpayments/v1/originalcredits/86dcb68d-cbd0-4878-8da7-ffc0e6554513"
                }
                ]
                 }
                ],
                "links": [
                 {
                    "rel": "self",
                    "href": "https://api.test.paysafe.com/cardpayments/v1/originalcredits?merchantRefNum=merchant 07.05.17_16&limit=2&offset=2&startDate=2017-01-14T15:12:18Z&endDate=2017-04-04T15:12:18Z"
                }
            ]
            }

# Group Customer APIs

## Create Profile [/v1/customers]

### Create Customer Profile [POST]

+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
                "firstName": "John",
                "lastName": "Smith",
                "phone" : "123-456-7890",
                "dateOfBirth": {
                    "year": 1981,
                    "month": 10,
                    "day": 24
                },
                "address": {
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON"
                },
                "email": "john.smith@email.com"
            }

+ Response 200 (application/json)

    + Body

            {
                "customerId": "Gt56fR6",
                "firstName": "John",
                "lastName": "Smith",
                "phone" : "123-456-7890",
                "dateOfBirth": {
                    "year": 1981,
                    "month": 10,
                    "day": 24
                },
                "address": {
                    "addressId": "DF45FDtrR",
                    "nickName": "Home",
                    "street": "100 Queen",
                    "street2": "Unit 200",
                    "city": "Toronto",
                    "zip": "M5H 2N2",
                    "country": "CA",
                    "state": "ON"
                },
                "email": "john.smith@email.com"
            }

## Modify Profile [/v1/customers/{customerId}]
### Associate a Payment Handle to a Customer [PUT]

+ Request (application/json)

    + Headers

            Authorization: "Basic YOUR-BASE64-ENCODED-API-KEY"
    
    + Body

            {
                "customerId": "Gt56fR6",
                "paymentHandleId" : ""
            }
+ Response 200 (application/json)

    + Body

            {
            
            }